---
dependencies: []

galaxy_info:
  author: 
  description:
  company: 
  license: 
  min_ansible_version: 
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - 18.04

  galaxy_tags:

