common_packages_redhat:
  - mosh
  - wget
  - openssl
  - unzip
  - bzip2
  - expect
  - at
  - tree
  - vim
  - screen
  - pwgen
  - git
  - htop
  - ImageMagick
  - inotify-tools
  - libselinux-python
  - libselinux-python3
  - yum-utils
  - gcc
  - jq
  - telnet
  - mlocate

common_packages_debian:
  - acl
  - mosh
  - curl
  - gnupg2
  - ca-certificates
  - lsb-release
  - wget
  - openssl
  - unzip
  - bzip2
  - expect
  - at
  - tree
  - vim
  - screen
  - git
  - htop
  - imagemagick
  - goaccess
  - jq
  - net-tools
  - mlocate
  - chrony
  - pwgen
