- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# display os version and image name
- name: Display os version
  shell: sudo echo  "System version:" "{{ansible_distribution}}" "{{ansible_distribution_version}}"  |sudo tee -a /data/logs/install_version.txt
 
- name: Display image name
  shell: sudo echo "Image name:" "{{image}}" |sudo tee -a /data/logs/install_version.txt
  when: image is defined and image is not none

- name: Show confirm if make images
  shell: sudo echo "本次在测试模式下运行，非特殊情况不能输入【0】来继续生产镜像！" |sudo tee -a /data/logs/install_version.txt 
  when: init == '0' or init == 0
  
- name: Check Docker Container Service
  shell: docker ps  --format \{\{'json .'\}\}| jq -s  map\(\{containername:'.Names',state:'.State'\}\)
  register: check_container_service
  notify: check_container_service

- name: Output all containers version
  shell: |
    wget -O /tmp/containers_version.sh https://websoft9.github.io/StackHub/scripts/containers_version.sh
    chmod +x /tmp/containers_version.sh
    bash /tmp/containers_version.sh
    rm -f /tmp/containers_version.sh
